# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 02:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chnnlsdmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 8, 2, 43, 38, 823308, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
